language: ruby
rvm:
  - 2.5.0
dist: trusty
services:
  - postgresql
script:
  - bundle update --bundler
  - bundle install
  - bundle exec bin/rails db:create
  - bundle exec bin/rails db:migrate
  - bundle exec rspec
